apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
     app: pvc-pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: hari-pvc